"""SQLAlchemy ORM models.

Every column type used here exists in both SQLite and PostgreSQL so the schema migrates
without change. JSON payloads carry the parts of the model that evolve fastest (state
snapshots, reward breakdowns, policy parameters).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def new_id() -> str:
    return uuid.uuid4().hex


class Base(DeclarativeBase):
    pass


class Run(Base):
    """A single orchestration episode."""

    __tablename__ = "runs"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    task: Mapped[str] = mapped_column(Text, nullable=False)
    policy: Mapped[str] = mapped_column(String(64), nullable=False, default="contextual_bandit")
    status: Mapped[str] = mapped_column(String(24), nullable=False, default="created")
    seed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    step_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cumulative_reward: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_cost: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_latency_ms: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    terminated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    termination_reason: Mapped[str | None] = mapped_column(String(128), nullable=True)
    config: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    current_state: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    initial_state: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    policy_state: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )

    states: Mapped[list["StateSnapshot"]] = relationship(
        back_populates="run", cascade="all, delete-orphan", order_by="StateSnapshot.step"
    )
    traces: Mapped[list["Trace"]] = relationship(
        back_populates="run", cascade="all, delete-orphan", order_by="Trace.step"
    )
    messages: Mapped[list["Message"]] = relationship(
        back_populates="run", cascade="all, delete-orphan", order_by="Message.step"
    )


class StateSnapshot(Base):
    """Immutable snapshot of the orchestrator state after a step."""

    __tablename__ = "states"
    __table_args__ = (
        UniqueConstraint("run_id", "step", name="uq_state_run_step"),
        Index("ix_states_run", "run_id"),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    run_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    step: Mapped[int] = mapped_column(Integer, nullable=False)
    entropy: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    payload: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    run: Mapped[Run] = relationship(back_populates="states")


class Trace(Base):
    """Observability record generated by every orchestration step."""

    __tablename__ = "traces"
    __table_args__ = (Index("ix_traces_run_step", "run_id", "step"),)

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    run_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    step: Mapped[int] = mapped_column(Integer, nullable=False)
    state_id: Mapped[str] = mapped_column(String(32), nullable=False)
    prev_state_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    action: Mapped[str] = mapped_column(String(48), nullable=False)
    agents: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    action_probability: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    transition_probability: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    action_distribution: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    outcome: Mapped[str] = mapped_column(String(24), nullable=False, default="success")
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    entropy_before: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    entropy_after: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    information_gain: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    reward: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    cumulative_reward: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    reward_breakdown: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    latency_ms: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    cost_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")

    run: Mapped[Run] = relationship(back_populates="traces")


class Message(Base):
    """Agent-to-agent communication emitted during a step."""

    __tablename__ = "messages"
    __table_args__ = (Index("ix_messages_run_step", "run_id", "step"),)

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    run_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    step: Mapped[int] = mapped_column(Integer, nullable=False)
    sender: Mapped[str] = mapped_column(String(48), nullable=False)
    receiver: Mapped[str] = mapped_column(String(48), nullable=False)
    kind: Mapped[str] = mapped_column(String(32), nullable=False, default="handoff")
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")
    weight: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    run: Mapped[Run] = relationship(back_populates="messages")


class Paper(Base):
    """A record in the Research Library."""

    __tablename__ = "papers"
    __table_args__ = (
        UniqueConstraint("source", "external_id", name="uq_paper_source_external"),
        Index("ix_papers_relevance", "relevance"),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    external_id: Mapped[str] = mapped_column(String(160), nullable=False)
    source: Mapped[str] = mapped_column(String(48), nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    abstract: Mapped[str] = mapped_column(Text, nullable=False, default="")
    authors: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    venue: Mapped[str] = mapped_column(String(255), nullable=False, default="")
    url: Mapped[str] = mapped_column(Text, nullable=False, default="")
    pdf_url: Mapped[str] = mapped_column(Text, nullable=False, default="")
    citation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    relevance: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")
    discovered_via: Mapped[str] = mapped_column(String(255), nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )

    tags: Mapped[list["PaperTag"]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )


class PaperTag(Base):
    """Tagging system row. ``category`` groups tags into the research taxonomy."""

    __tablename__ = "paper_tags"
    __table_args__ = (
        UniqueConstraint("paper_id", "tag", name="uq_paper_tag"),
        Index("ix_paper_tags_tag", "tag"),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    paper_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    tag: Mapped[str] = mapped_column(String(96), nullable=False)
    category: Mapped[str] = mapped_column(String(96), nullable=False, default="")
    score: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)

    paper: Mapped[Paper] = relationship(back_populates="tags")


class Citation(Base):
    """Directed edge of the citation graph."""

    __tablename__ = "citations"
    __table_args__ = (
        UniqueConstraint("source_paper_id", "target_paper_id", name="uq_citation_edge"),
        Index("ix_citations_source", "source_paper_id"),
        Index("ix_citations_target", "target_paper_id"),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    source_paper_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    target_paper_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    relation: Mapped[str] = mapped_column(String(32), nullable=False, default="cites")
    weight: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)


class ProviderQuery(Base):
    """Audit log of research provider calls (used by the observability page)."""

    __tablename__ = "provider_queries"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    provider: Mapped[str] = mapped_column(String(64), nullable=False)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    result_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    degraded: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    latency_ms: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    error: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)


class PolicyProfile(Base):
    """Learned policy parameters that outlive a single episode.

    A run constructs a fresh policy by default, so nothing carries between tasks. A profile is
    the router's memory: train it in simulation with tools/campaign.py, then load it to route
    real work. ``signature`` pins the shapes the weights were fitted for, because LinUCB's ridge
    matrices are feature_dim x feature_dim and silently loading a stale one would corrupt it.
    """

    __tablename__ = "policy_profiles"
    __table_args__ = (UniqueConstraint("name", "policy", name="uq_profile_name_policy"),)

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column(String(64), nullable=False)
    policy: Mapped[str] = mapped_column(String(64), nullable=False)
    signature: Mapped[str] = mapped_column(String(128), nullable=False)
    state: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    episodes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_steps: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cumulative_reward: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    mean_episode_reward: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )


class PairwiseVerdict(Base):
    """A blind preference between two arms on the same task.

    Absolute scoring compresses: a judge rating one answer at a time drifts to the top of the
    range, and the gap between arms disappears into rounding. A real experiment here produced
    0.96 against 0.98, which is noise between two scorings rather than a difference.

    Pairwise preference avoids that by never asking for an absolute number. The judge sees both
    answers without knowing which arm produced them and picks one, which is the comparison
    protocol used by MT-Bench and Chatbot Arena.
    """

    __tablename__ = "pairwise_verdicts"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    experiment: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    run_a_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    run_b_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    winner: Mapped[str] = mapped_column(String(8), nullable=False)
    """``a``, ``b`` or ``tie``. Ties are kept, not dropped: they are evidence of no difference."""
    judge: Mapped[str] = mapped_column(String(64), nullable=False, default="human")
    rubric: Mapped[str] = mapped_column(Text, nullable=False, default="")
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)


class RunVerdict(Base):
    """An external judgment of how good a run's answer was.

    Cost, latency and tokens are measured automatically, but they only tell you what an arm
    *spent*. Whether the answer improved has to come from outside the reward function, which
    rewards belief collapse and would otherwise let orchestration win by construction.

    Kept in its own table rather than as columns on ``runs`` so the schema stays additive:
    ``create_all`` creates new tables but will not add columns to an existing one.
    """

    __tablename__ = "run_verdicts"
    __table_args__ = (UniqueConstraint("run_id", "judge", name="uq_verdict_run_judge"),)

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    run_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, index=True
    )
    judge: Mapped[str] = mapped_column(String(64), nullable=False, default="human")
    score: Mapped[float] = mapped_column(Float, nullable=False)
    """0-1. Comparable across arms only if the same rubric was applied to each."""
    rubric: Mapped[str] = mapped_column(Text, nullable=False, default="")
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
